{{- if .Values.certmanager.enabled }}
{{- if .Values.certmanager.useSelfSignedIssuer }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Release.Name }}-cluster-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-ca-certificate
  namespace: {{ .Release.Namespace }}
spec:
  isCA: true
  commonName: {{ .Release.Name }}-self-signed-ca
  secretName: {{ .Release.Name }}-root-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ .Release.Name }}-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Release.Name }}-issuer
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: {{ .Release.Name }}-root-ca-secret
{{- end }}
{{- range .Values.ingress.tls }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $.Release.Name }}-tls-certificate-{{ .secretName}}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .secretName }}
  dnsNames:
  {{ .hosts | toYaml | indent 6 }}
  {{- if $.Values.certmanager.useSelfSignedIssuer }}
  issuerRef:
    name: {{ $.Release.Name }}-issuer
    kind: Issuer
    group: cert-manager.io
  {{- else }}
  issuerRef:
    name: {{ required "certmanager.issuerName is required when not using self signed issuer" $.Values.certmanager.issuerName }}
    kind: ClusterIssuer
    group: cert-manager.io
  {{- end }}
{{- end }}
{{- end }}
