{{- if not .Values.redisExistingSecretName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-internal-redis
  annotations:
    "helm.sh/hook": pre-install
data:
  redisPassword: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}

{{- if not .Values.postgresExistingSecretName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-internal-postgresql
  annotations:
    "helm.sh/hook": pre-install
data:
 repmgr-password: {{ randAlphaNum 32 | b64enc | quote }}
 postgresql-password: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}


{{- if not .Values.pgpoolExistingSecretName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-internal-pgpool
  annotations:
    "helm.sh/hook": pre-install
data:
 admin-password: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}