{{- if not .Values.redisExistingSecretName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-internal-redis
  annotations:
    "helm.sh/hook": pre-install
data:
  redisPassword: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
{{- if not .Values.mongoDbExistingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-internal-mongodb
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  mongodb-root-password: {{ randAlphaNum 16 | b64enc | quote }}
  mongodb-password: {{ randAlphaNum 16 | b64enc | quote }}
  mongodb-replica-set-key: {{ randAlphaNum 16 | b64enc | quote }}
{{- end }}
{{- if not .Values.fetchCredentialsSecretName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-internal-hermes-fetch
type: Opaque
data:
  username: {{ .Values.fetchUsername | b64enc | quote }}
  password: {{ .Values.fetchPassword | b64enc | quote }}
{{- end }}