imagePullPolicy: IfNotPresent
image:
  tag: local
kafka:
  replicaCount: 1
  defaultReplicationFactor: 1
  offsetsTopicReplicationFactor: 1
  transactionStateLogReplicationFactor: 1
  zookeeper:
    replicaCount: 1