name: Lint and Test Charts
on:
  pull_request:
    paths:
      - 'helm/**'
      - '.github/workflows/helm-qa.yml'
      - '.github/ct.yml'
      - '.github/helm-docs.sh'
      - '.github/kubeval.sh'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true
jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Helm
        uses: azure/setup-helm@v2.1
        with:
          version: v3.7.1
      - uses: actions/setup-python@a69041ca9f9f72c33ce94580dd70191dd501c392
        with:
          python-version: 3.7
      - name: Install chart-testing
        uses: helm/chart-testing-action@c027be8bc4049de5fee5d05cb300bcbbdebb2903
        with:
          version: v3.4.0
      - name: Run lint
        run: ct lint --config .github/ct.yml
  lint-docs:
    runs-on: ubuntu-latest
    needs: lint-chart
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run helm-docs
        run: .github/helm-docs.sh
  kubeval-chart:
    runs-on: ubuntu-latest
    needs:
      - lint-chart
      - lint-docs
    strategy:
      matrix:
        k8s:
          - v1.21.9
          - v1.22.6
          - v1.23.3
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run kubeval
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
        run: .github/kubeval.sh
  install-chart:
    name: install-chart
    runs-on: ubuntu-latest
    needs:
      - lint-chart
      - lint-docs
      - kubeval-chart
    strategy:
      matrix:
        k8s:
          - v1.21.2
          - v1.22.5
          - v1.23.3
    steps:
      - name: Checkout
        uses: actions/checkout@v3 
        with:
          fetch-depth: 0

      - name: Create kind ${{ matrix.k8s }} cluster
        uses: helm/kind-action@deab45fc8df9de5090a604e8ec11778eea7170bd
        with:
          node_image: kindest/node:${{ matrix.k8s }}
          version: v0.11.1 

      - name: Install chart-testing
        uses: helm/chart-testing-action@c027be8bc4049de5fee5d05cb300bcbbdebb2903 
        with:
          version: v3.4.0 

      - name: Run chart install
        run: ct install --config .github/ct.yml