name: Bump Helm Version
on:
  push:
    branches:
      - main
    paths:
      - "helm/**"
      - ".github/workflows/helm-release.yml"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm ci
      - name: Bump Helm Version
        run: |
          node scripts/bumpHelmVersion.js
          git add .
          git commit -m "Bump Helm Version"
          git push
      - name: Trigger Release
        run: |
          node scripts/triggerHelmRelease.js
        